### ISSUE TITLE
Emulationstation performance drop after bump up to new version

### ISSUE THREAD

**Issue by asakous** [asakous/EmuELEC-H3#10]
There is noticeable performance drop during scrolling  between two systems in Emulationstation.
top program shows Emulationstation process eats a lot of CPU power.
I am not sure with cause the problem, new theme or  Emulationstation program itself .

**Comment by shantigilbert** [comment]
Can you try another theme? do you know which version started with this issue? maybe we can find a solution

**Comment by asakous** [comment]
before bump version is "c9668fb09e7afab04925ea3618f5d1ba475726d1"	
I will install a new theme and see what differences

**Comment by asakous** [comment]
I believe it's a es-theme-carbon UI configuration  problems. I tune off  some animation and transition settings then scrolling system become more fluent.
