### ISSUE TITLE
I think mkimage script is wrong (can't boot resulting image) 

### ISSUE THREAD

**Issue by shantigilbert** [asakous/EmuELEC-H3#7]
Image does not boot on OpiPC it hangs on the EmuELEC Splash, are there any special instructions to make it boot? note, the one on "releases" does not boot either

I think the mkimage script might be wrong.

The resulting partition is called: 
`LIBREELEC` and `33 MB VOLUME` 

it should be:
`EMUELEC` and `STORAGE` 

But I cannot seem to find a solution, is this script correct?

**Comment by asakous** [comment]
releases one should boot . if I did not make some mistakes. I will double check it sometime this night.
and the problem you mentioned is that Libreelec use host tools to make image, so when host linux  has new ext4 features such as 64bit and metadata_csum  it will not boot due to old kernel dosen't support new ext4 features.

**Comment by shantigilbert** [comment]
I have the same problem on the release and the one I compile, I think I found the solution for the partitions, but not for the booting problem. 

can we temporarily disable the 64bit and metadata_csum while building?

**Comment by asakous** [comment]
in /etc/mke2fs.conf 
I removed new features. see below 
        ext4 = {
                features = has_journal,extent,huge_file,flex_bg,uninit_bg,dir_nlink,extra_isize
                 auto_64-bit_support = 1
                inode_size = 256
        }

**Comment by asakous** [comment]
and I use old e2fsprogs(1.42.12) to make Image . maybe it helps

**Comment by shantigilbert** [comment]
Maybe you can compile one with the new changes and test it later? I cannot get it to boot, I made the changes to mke2fs.conf, still does not boot :(

**Comment by asakous** [comment]
can you try one more time by using old  e2fsprogs(1.42.12) and modify mkimage script change mke2fs tune2fs e2fsck to old version.

**Comment by asakous** [comment]
I just compile new one and It boots.(without patches). I using old e2fsprogs .I suspect this cause problem. I mean e2fsprogs  version.

**Comment by shantigilbert** [comment]
Can you share your image?

**Comment by SumavisionQ5** [comment]
> Can you share your image?

Here:
https://github.com/asakous/EmuELEC-H3/releases
asakous has updated it.

**Comment by asakous** [comment]
I am compiling the newest source code and see what's going on that  @shantigilbert encountered

**Comment by shantigilbert** [comment]
That image (updated) does boot! but it has no audio, not sure why I cannot make a bootable image :/

Anyways I started a new branch with Lakka as base, I got everything to compile but there is no SDL video, I am recompiling right now with a few changes and hopefully it will display video.

**Comment by asakous** [comment]
@shantigilbert I thought Emulationstation has no audio or bgm is correct.

**Comment by shantigilbert** [comment]
Emulationstation does have audio (on Amlogic), and it also support BGM from (/storage/roms/BGM) but the image at least for me has no audio even on emulators. not sure if its something on my side tho.

**Comment by asakous** [comment]
@shantigilbert  You have to select correct audio out put device in Retroarch menu. yesterday I faced same problem.

**Comment by asakous** [comment]
I have tried every single audio option in Emulationstation config menu. I still can't make some noise.maybe Emulationstation need some patches for H3 kernel.

**Comment by shantigilbert** [comment]
I get sound on Emulationstation, but its not correct, it plays for one second and stops for one second then it plays again, I will try to make a video.

There might be a problem with SDL2 (which is what plays audio) or pulseaudio for H3

**Comment by shantigilbert** [comment]
@asakous using your changes to EmuELEC and Lakka as base I managed to make a working version (almost working) of EmuELEC. 

Boots perfectly fine and audio works but the gamepads (joysticks) are not being recognized. 

https://github.com/EmuELEC/EmuELEC-H3/tree/Lakka_base

We can merge it to master if you have no objection.

**Comment by asakous** [comment]
@shantigilbert I make some changes. and now image can boot without any problem. if you want to try , please make sure toolchain version of e2fsprogs has beed changed.

**Comment by shantigilbert** [comment]
Awesome! will try it later and report back

**Comment by asakous** [comment]
@shantigilbert  I remember that new kernel has image tearing problem and performance not as good as old kernel one .if my memory not lie to me

**Comment by shantigilbert** [comment]
The few games I tested ran really good, but I am having other problems, so I guess its not a good idea to change. But maybe we could use Lakka 2.3.1 as base, that one still uses the old Kernel. 

Anyways I need to compile from scratch to test your new changes, so I will test them tomorrow (12:30 night here)

**Comment by shantigilbert** [comment]
or maybe you could upload an image with the new changes ?

**Comment by asakous** [comment]
I already made one few months ago. base on Lakka 2.3.1 and still using  old kernel 3.4.113

**Comment by asakous** [comment]
new image will be uploaded. please wait.

**Comment by shantigilbert** [comment]
New image works almost perfect! sound still has some minor issues, on my Orange Pi PC the HDMI audio device is 1,0 not sure if all H3 devices are the same, but maybe we could default it to that ? 

There is also a small issue with pulseaudio (I think) where the rom will not load and the system hangs, but I am trying to figure that one out, if I find a solution I will open a PR. 

Thanks! this issue should be closed as the booting has been resolved!
